name: "1.System Requirement"
description: "Form to capture requirements."
assignees:
  - "" # Add default assignee here if applicable
projects:
  - "Development"
title : "[GNEO-SOW-2-FRS-001] Geographical areas and water bodies of interest"
type: "Requirement"
body:
  - type: textarea
    id: requirement-id
    attributes:
      label: "Related/Mapped Requirement ID(s)"
      description: "Requirement ID(s) based on the user, functional and security requirements, and system requirements specification documents"
      placeholder: "Provide the requirement ID(s) separated by commas that are related to/mapped with the current requirement. Example: GNEO-SOW-1-FRS-001,GNEO-SOW-1-URS-001"
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Description of the current requirement derived by the deliverables and requirement reviews"
      placeholder: "Provide a detailed description"
  - type: textarea
    id: vv_instructions
    attributes:
      label: "Validation/Verification Instructions"
      description: "Instructions to perform the VV test(s)"
      placeholder: "List VV instructions per process"
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Rules"
      description: "Document the acceptance rules of of the current requirement"
      placeholder: "The VV tests for all processes MUST have pass the respective acceptance criteria"
  - type: textarea
    id: testing_procedure
    attributes:
      label: "Remarks"
      description: "Record any problems, modifications, or any other note, raised during the VV procedure"
      placeholder: "Provide any procedural remarks"
  - type: dropdown
    id: test_results
    attributes:
      label: "Decision"
      description: "Select whether the current requirement has been accomplished or not"
      options:
        - Pass
        - Fail
    validations:
      required: false
