name: "5.Nonconformity"
description: "Report a deviation from requirements, standards, or stakeholder expectations"

assignees: ["keradin"]
labels: []
projects: ["A3W-HELOISA/Development"]
title: "NC-[###]: <Short description of issue>"
type: 5.Nonconformity

body:
  - type: markdown
    attributes:
      value: |
        ## Non-Conformity Definition
        Please fill out all relevant fields below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Concise description of the non-conformity
      placeholder: "Describe the deviation, affected system, or process"
    validations:
      required: true

  - type: textarea
    id: containment
    attributes:
      label: Immediate containment actions
      placeholder: "What steps were taken immediately?"

  - type: textarea
    id: rootcause
    attributes:
      label: Root Cause Analysis
      placeholder: "Describe investigation steps or findings"

  - type: textarea
    id: corrective
    attributes:
      label: Corrective Action Plan
      placeholder: "Steps to resolve and prevent recurrence"

  - type: textarea
    id: verification
    attributes:
      label: Verification
      placeholder: "How will QA team verify corrective actions?"

  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: "Any additional remarks"

