name: "Minutes of Meeting (MoM)"
description: "Document the details, decisions, and action items from a meeting"
assignees: ["Keradin"]
labels: []
projects: ["ORG/Development"]
title: "MoM: [Date or Topic]"
type: "Minutes of meeting"
body:
  - type: markdown
    attributes:
      value: |
        ## 🗓️ Minutes of Meeting (MoM)
        Please fill in all relevant fields below to ensure the meeting is properly documented.
  - type: input
    id: date
    attributes:
      label: Meeting Date
      description: "Date of the meeting"
      value: "2025-mm-dd"
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Meeting Time
      description: "Start - End time and time zone"
      value: "11:00 – 12:30 EET"
  - type: input
    id: location
    attributes:
      label: Location / Platform
      description: "Specify the meeting location or online platform"
      value: "Google Meet / MS Teams / Athens Office / HSC"
  - type: textarea
    id: attendees
    attributes:
      label: Attendees
      description: "List all participants and their affiliations"
      value: |
        - Maria Kremezi
        - Kosta Vlachos
        - Stelios Kossieris
        - Andreas Karavias
        - George Keradinidis
    validations:
      required: true
  - type: textarea
    id: agenda
    attributes:
      label: Agenda
      description: "List the key topics covered in the meeting"
      value: |
        - Review of last meeting action items
        - Update on E.O. modules
        - Update on development modules 
        - Update on integration status
        - ESA requests
        - A1.1 data update
        - A1.2 data update
        - A2 data update
        - Planet data update
  - type: textarea
    id: actions
    attributes:
      label: Action Items
      description: "Action, Responsible, Deadline"
      value: |
        - , , 
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: "Add any supporting remarks, files discussed, or follow-up topics"
      placeholder: "Add any additional information here..."
