name: "Minutes of Meeting (MoM)"
description: "Document the details, decisions, and action items from a meeting"
title: "MoM: [Date or Topic]"
labels: ["Meeting", "Minutes"]
projects: ["ORG/Project-Management"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🗓️ Minutes of Meeting (MoM)
        Please fill in all relevant fields below to ensure the meeting is properly documented.

  - type: input
    id: date
    attributes:
      label: Meeting Date
      description: "Specify the date of the meeting (YYYY-MM-DD)"
      placeholder: "2025-10-07"
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: Meeting Time
      description: "Start time and time zone"
      placeholder: "11:00 – 12:30 EET"

  - type: input
    id: location
    attributes:
      label: Location / Platform
      description: "Specify the meeting location or online platform"
      placeholder: "MS Teams / ESA HQ / Athens Office"

  - type: textarea
    id: attendees
    attributes:
      label: Attendees
      description: "List all participants and their affiliations"
      placeholder: |
        - Maria Kremezi
        - Kosta Vlachos
        - Stelios Kossieris
        - Andreas Karavias
        - George Keradinidis
    validations:
      required: true

  - type: textarea
    id: agenda
    attributes:
      label: Agenda
      description: "List the key topics covered in the meeting"
      placeholder: |
        1. Review of last meeting actions  
        2. Update on Water Quality Module  
        3. Next milestone deliverables  
        4. Open issues and planning

  - type: textarea
    id: discussion
    attributes:
      label: Discussion Summary
      description: "Summarize the discussion points, decisions made, and rationales"
      placeholder: |
        - 

  - type: textarea
    id: decisions
    attributes:
      label: Key Decisions
      description: "Document all major decisions or agreements made during the meeting"
      placeholder: |
        - Decision 1: 
        - Decision 2: 

  - type: textarea
    id: actions
    attributes:
      label: Action Items
      description: "List all actions, responsible persons, and deadlines"
      placeholder: |
        Action, Responsible, Deadline
         , , 
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: "Add any supporting remarks, files discussed, or follow-up topics"
      placeholder: "Add any additional information here..."
