name: "Requirement"
description: "Form to capture requirements."
assignees:
  - "" # Add default assignee here if applicable
projects:
  - "Development"
title : "The system shall xxx"
type: "Requirement"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "In-depth analysis of the requirement"
      placeholder: "Provide a detailed description"
  - type: textarea
    id: vv_instructions
    attributes:
      label: "Validation/Verification testing instructions"
      description: "Instructions to perform the required test"
      placeholder: "List possible instructions"
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance criteria"
      description: "Document the acceptance criteria of requirement fulfillment"
      placeholder: "Provide the acceptance criteria"
  - type: textarea
    id: testing_procedure
    attributes:
      label: "Remarks during testing procedure"
      description: "Record any problems, modifications, or any other note, raised during the tesing procedure"
      placeholder: "Provide the procedural remarks"
  - type: textarea
    id: test_results
    attributes:
      label: "Test results"
      description: "Record test results"
      placeholder: "Provide the test results"
